repos:
-   repo: local
    hooks:
    - id: pyright
      name: pyright
      entry: pyright .
      language: system
      types: [python]
      pass_filenames: false
    
    - id: black
      name: black
      entry: black --check .
      language: system
      types: [python]
      pass_filenames: false
