from core import Const, Item, ItemRarity, CraftDict


items = Const([
    Item(
        name="Монеты",
        strength=0,
        rarity=ItemRarity.COMMON,
        desc="Монеты используются как игровая валюта.",
    ),
    Item(
        name="Дерево",
        price=10,
        strength=0,
        rarity=ItemRarity.COMMON,
        desc="Дерево может быть использовано для строительства или изготовления предметов.",
    ),
    Item(
        name="Вода",
        price=10,
        strength=0,
        rarity=ItemRarity.COMMON,
        desc="Вода необходима для выживания персонажа.",
    ),
    Item(
        name="Железо",
        price=15,
        strength=0,
        rarity=ItemRarity.COMMON,
        desc="Железо может быть использовано для ковки оружия и брони.",
    ),
    Item(
        name="Уголь",
        price=15,
        strength=0,
        rarity=ItemRarity.COMMON,
        desc="Уголь используется в печах и кузницах.",
    ),
    Item(
        name="Лутбокс",
        price=100,
        strength=0,
        rarity=ItemRarity.UNCOMMON,        desc="Лутбоксы содержат разнообразные сокровища.",
    ),
    Item(
        name="Рыба",
        price=30,
        strength=0,
        rarity=ItemRarity.COMMON,
        desc="Рыбу можно приготовить и съесть для восстановления здоровья.",
    ),
    Item(
        name="Яблоко",
        price=10,
        strength=0,
        rarity=ItemRarity.COMMON,
        desc="Яблоко можно съесть для восстановления здоровья.",
    ),
    Item(
        name="Камень",
        price=12,
        strength=0,
        rarity=ItemRarity.COMMON,
        desc="Камень можно использовать для строительства и изготовления инструментов.",
    ),
    Item(
        name="Золото",
        price=42,
        strength=0,
        rarity=ItemRarity.UNCOMMON,
        desc="Золото используется для изготовления драгоценных украшений и предметов.",
    ),
    Item(
        name="Кристалл",
        price=67,
        strength=0,
        rarity=ItemRarity.RARE,
        desc="Кристаллы обладают магической энергией и могут использоваться для создания заклинаний.",
    ),
    Item(
        name="Кожа",
        price=17,
        strength=0,
        rarity=ItemRarity.COMMON,
        desc="Кожу можно использовать для создания брони и предметов одежды.",
    ),
    Item(
        name="Алмаз",
        price=71,
        strength=0,
        rarity=ItemRarity.EPIC,
        desc="Алмазы являются одними из самых ценных драгоценных камней.",
    ),
    Item(
        name="Череп",
        price=40,
        strength=0,
        rarity=ItemRarity.COMMON,
        desc="Черепы могут использоваться в ритуалах и алхимии.",
    ),
    Item(
        name="Кость",
        price=30,
        strength=0,
        rarity=ItemRarity.COMMON,
        desc="Кости могут использоваться для создания инструментов и украшений.",
    ),
    Item(
        name="Нить",
        price=20,
        strength=0,
        rarity=ItemRarity.COMMON,
        desc="Нить может использоваться для шитья и создания одежды.",
    ),
    Item(
        name="Листья",
        price=4,
        strength=0,
        rarity=ItemRarity.COMMON,
        desc="Листья можно использовать для создания зелий и алхимических смесей.",
    ),
    Item(
        name="Топор",
        price=15,
        strength=20,
        rarity=ItemRarity.UNCOMMON,
        craft=[
            CraftDict(name="Дерево", quantity=5),
            CraftDict(name="Железо", quantity=3),
        ],
        desc="Топор может быть использован для рубки деревьев и сражений.",
    ),
    Item(
        name="Кирка",
        price=15,
        strength=20,
        rarity=ItemRarity.UNCOMMON,
        craft=[
            CraftDict(name="Железо", quantity=5),
            CraftDict(name="Дерево", quantity=3),
        ],
        desc="Кирка может быть использована для добычи ресурсов и сражений.",
    ),
    Item(
        name="Меч",
        price=25,
        strength=30,
        rarity=ItemRarity.UNCOMMON,
        craft=[
            CraftDict(name="Железо", quantity=2),
            CraftDict(name="Дерево", quantity=1),
        ],
        desc="Меч является мощным оружием для сражений.",
    ),
    Item(
        name="Ведро",
        price=5,
        strength=10,
        rarity=ItemRarity.UNCOMMON,
        craft=[
            CraftDict(name="Железо", quantity=3),
        ],
        desc="Ведро может быть использовано для переноски жидкостей.",
    ),
    Item(
        name="Лодка",
        price=50,
        strength=40,
        rarity=ItemRarity.UNCOMMON,
        craft=[
            CraftDict(name="Железо", quantity=2),
            CraftDict(name="Дерево", quantity=3),
        ],
        desc="Лодка позволяет перемещаться по воде.",
    ),
    Item(
        name="Удочка",
        price=8,
        strength=10,
        rarity=ItemRarity.UNCOMMON,
        craft=[
            CraftDict(name="Железо", quantity=5),
            CraftDict(name="Нить", quantity=2),
        ],
        desc="Удочка используется для ловли рыбы.",
    ),
]
)
