name: Checks
on:
    push:
        branches:
            - main
  
jobs:
    check:
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v2

        - name: Install requirements
          run: pip install -r requirements.txt && pip install pyright
        
        - name: Pyright chack
          run: pyright ./Adventures
        
        