name: Checks
on: [push]

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install requirements
        run: |
          pip install -r requirements.txt
          pip install pyright
          pip install black

      - name: Pyright check
        run: pyright ./Adventures

      - name: Black check
        run: black --check .